= Scania
:nofooter:

== Introduction

== Marks

[id=m1,reftext=1]
=== Mark 1

1975 -> 1981 

[id=m2,reftext=2]
=== Mark 2

1980 -> 1989

Scania Series-2, also known as GPRT range.
Had three type of chassis duty levels (the size of the chassis rails were the same, just thicker walls and an additional inner rails in the E level): 

* M = Medium duty
* H = Heavy duty
* E = Extra-heavy duty

The chassis type appeared following the numeric model designation, e.g. 142H.

Had four type of cabs:

* P = Low cab (only available as a day cab?)
* R = High cab
* T = Bonneted cab (a.k.a "Torpedo")

A low-mounted G cab was available too on the M chassis. Had only two steps vs three for the P cab.

Available models were 82, 112, 142. The last digit ("2") is the series, the first one or two digits are the engine displacement (approximately) in liters.

A R 142 V8 version with Intercooler was introduced in 1983. To accomodate the intercooler (smaller radiator installed infront of the main radiator) the front panel of the cab (the grille) was moved forward 5cm and the panel on which the large "SCANIA" logo is embedded became angled instead of totally vertical as on the non-intercooler versions. The hood of the T model was extended too <<b6>>.

[id=m3,reftext=3]
=== Mark 3

1987 -> 1998

Minor visual changes to the cabs and more major upgrades to the drivetrain.

A new badge with the engine horsepowers were added to the lower grille on the port side.

The "Streamline" cab was added in 1991 as an option.

[id=m4,reftext=4]
=== Mark 4

1996 -> 2005 (2007 in Brazil)

Scania Series-4 trucks saw major changes from the previous series. The cabs are more rounded, new engines and new chassis and suspensions.

The letter following the digits in the model designation now stands for the vehicle class:

* D = Local deliveries
* L = Long-distance transport
* C = Construction (heavy duty with high ground clearnce)
* G = General purpose (heavy duty)

[id=m5a,reftext=5a]
=== Mark 5a

2004 -> 2009

Major upgrades with many visual and interanl differences.

Scania stopped using the "Series n" designation. I don't think that this generation has an "official" name but it is sometimes called "PRT-range"\"PGRT-range" after the cab types that were offered. 

The T cab (bonneted) was discountiued in 2005.

The G cab (medium height between the P and the R) added in 2007.

Sometimes referred to as "Series 5"

=== Mark 5b

2009 -> 2013

Facelift. Upgraded grille, cab interior and other modifications.
Sometimes referred to as "Series 6"

=== Mark 5c

2013 -> 2017

Streamline G and R cab versions without the air intakes on the sides.

[id=m6,reftext=6]
=== Mark 6

2016 -> present

Also known as "Next Generation Scania". 
No common parts in the new R and S cab with the previous mark <<b5>>.

The S cab (with completely flat floor) and the L cab (extra low mounted cab for applications like garbage collection) were add to the range which is called the "LPGRS-range".

Added the XT option for extra heavy offroad applications.

== Suspensions

=== Bell crank

Double-drive tandem with four steel leaf springs (2 on each side) that are connected by rods and bell cranks.

Available on Mark <<m1>> and <<m2>> (on M chassis)

=== Heavy balance beam

Available on Mark <<m2>> and <<m3>> (maybe also on Mark <<1>> - not sure) on the H and E chassis

Double drive with trapezoid springs with 8, 10 or 12 leaves.

Distance between axles: 1350mm.

=== BT200

Available on Mark <<m3>> and <<m4>> on the M chassis.

Lighter double-drive suspension with trapezoid (or parabolic?) steel springs.

=== BT201\BT300

Available on Mark <<m4>> and forward.

Heavy duty double-drive with trapezoid or parabolic steel springs.

Distance between axles: 1350mm.

=== 6x2 tag steel springs

Available on Mark <<m2>> and <<m3>>.

Provided in the 6x2 Italeri kits (very good facsimile).

=== 6x4 air bags

=== 6x2 tag air bags

== Kits

Most of Scania marks (since mark 2) were offered by Italeri. Mostly as tractors, some as rigid. Marks 2 and 3 were offered as 6x2 tractors and ridigs but mark 4 and forward were offered only as a 4x2.

[cols="1,2,5,1"]
|===
|Kit #|Manufacturer|Name|Mark


|link:https://www.scalemates.com/kits/italeri-755-turbo-truck--157500[755]
|Italeri
|Turbo Truck
|<<m2>>
|link:https://www.scalemates.com/kits/italeri-743-scania-r-144--157492[743]
|Italeri
|Scania R 144
|<<m4>>
|link:https://www.scalemates.com/kits/italeri-3927-scania-s730-highline-4x2--1029942[3927]
|Italeri
|Scania S730 Highline 4x2
|<<m6>>
|link:https://www.scalemates.com/kits/italeri-3961-scania-s770-4x2-normal-roof--1469658[3961]
|Italeri
|Scania S770 4x2 Normal Roof
|<<m6>>

|===

[bibliography]
== References

* [[[b1,1]]] link:https://en.wikipedia.org/wiki/Scania_2-series[Scania 2-series] 
Wikipedia
* [[[b2,2]]] link:https://en.wikipedia.org/wiki/Scania_3-series[Scania 3-series] 
Wikipedia
* [[[b3,3]]] link:https://en.wikipedia.org/wiki/Scania_4-series[Scania 
4-series] Wikipedia
* [[[b4,4]]] link:https://forum.truckersmp.com/index.php?/topic/109971-questions-about-scania-trucks/[Questions about Scania trucks] TruckersMP forum, September 12, 2022
* [[[b5,5]]] link:https://www.scania.com/content/dam/scanianoe/global/eventcontent/2016/2016-08-23-next-generation-scania/pressreleases-pdf/english/New-truck-range---exterior.pdf[Scania's new truck range provides more
of everything] Scania Press Release, August 23, 2016
* [[[b6,6]]] link:https://truckinfocus.com/encyclopedia/history/the-scania-chronicle?page=6[The Scania Chronicle (page 6)] TruckInFocus.com