= Wheels and tyres
:nofooter:

== Inner tube\Tubeless

Older tyres require the use of an inner tube from softer rubber. Newer tyres don't use a tube - tubeless. The seal between the tyre itself and the wheel is good enough to hold the air.

== Wheels (rims)

The shape of the rim profil is different between tube and tubeless tyres and also the wheel sizes for tubed tyres are usually different from wheels for tubeless. Rims sizes that ends with ".5" (half an inch), like 22.5 or 24.5 are usally for tubeless while whole number wheels like 22 or 24 are often for tubed tyres.

[id=wheel_diameters,reftext=here]
=== Diameters

There are several standard diameters of wheels:

[cols="1,2,7"]
|===
|Diameter (inches)|Tube type|Comment

|17
|Inner tube
|For lowloaders and Maxi trailers

|19.5
|Tubeless
|Light trucks

|20
|Inner tube
|

|22
|Inner tube
|Most common size in the past.

|22.5
|Tubeless
|Most common current size in US and Europe.

|24
|Inner tube
|For heavy duty application.

|24.5
|Tubeless
|For heavy duty application.

|===

=== Width

The width of the rim needs to related to the width of the tyre but most tyres can be fitted on several rim widths.

The rim width is usually 2-4 inches narrower than the tyre

==== Common widths

|===
|Rim width (inches)|Common rim diameters|Common tyres widths (inches or mm)|Comment

|7.50
|17, 17.5, 19, 19.5, 20, 22.5, 24.5
|10, 11, 235, 245, 255, 265, 275, 285
|Common in the 80s but still used today in low-loaders and high cube trailers

|8.25
|19.5,  22.5, 24.5
|10, 11, 12, 255, 265, 275, 285
|

|9.00
|22.5, 24.5
|12, 13, 295, 315
|Most common on heavy trucks since the 2000s

|11.75
|22.5, 24.5
|385
|Common for super single

|12.25
|22.5, 24.5
|385
|Common for super single

|===

== Tyres\Tires

=== Radial\Crossply

The most common modern tyres are radial - the belts inside the tyres run parallel to the tyre. Older tyres (and tyres for agricultural tractors) are crossply - the belts in the tyres run in a criss-cross pattern.

=== Thread patterns

The tyre thread is selected based on the tyre mission. Different patterns are optimized for steering axles, drive axles or trialers but some tyres come with universal pattern.

=== Sizes

There are two systems to measure tyres sizes, the P-Metric and the imperial.

==== P-Metric

www/hhRwheel_size

* www - Tyre section width. The width of the tyre at the widest section in millimeters. The tread itself is narrower.
* hh - Aspect ratio. The height of the tyre wall as percents of the tyre width. Also known as the tyre profile.
* R = radial (tubeless). - (dash) = crossply
* wheel_size - the wheel size as described <<wheel_diameters>>

===== Common P-Metric tyre sizes

[col="1,1,1,5"]
|===
|Size|Width (mm)|Wall height (mm)|Comment

|295/80R22.5
|295
|295*80%=236
|Most common older tyre

|315/80R22.5
|315
|315*80%=252
|Common older tyre for heavy haulage

|315/70R22.5
|315
|315*70%=220.5
|Common modern tyre for drive axles

|385/65R22.5
|385
|385*0.65=250
|Common modern for steering axles - a.k.a. "super single"

|===

==== Imperial

The tyre wall height is not given explicitly. Sometime the overall diameter of the tyre is given (in inches) at the begning as in 33x12R22.5 = 33 inches.

When the tyre size is written with a dot and two zeros the aspect ratio is very close to 100%. Otherwise a default of 88% is often assumed.

===== Common Imperial tyre sizes

[col="1,1,1,5"]
|===
|Size|Width (inches)|Wall height (inches)|Comment

|12R22.5
|12
|12*88%=10.56
|

|12.00R22.5
|12
|12*100%=12
|

|14R24.5
|14
|14*88%=12.32
|Common tyre for heavy haulage
|===

== 1/24-1/25 scale models wheels and tyres

[col="4,1,4"]
|===
|Description|Closest actual size|Comment

|Italeri modern rubber super single tyre
|385/65R22.5
|

|Italeri modern rubber tyre
|
|

|Italeri modern rubber trailer tyre
|
|

|Italeri old plastic tyre
|
|Better but still shallow thread

|Italeri very old plastic tyre
|
|Very shallow thread

|===